# SPDX-FileCopyrightText: 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

# These are supported funding model platforms

github: AliSajid # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: asimami
buy_me_a_coffee: asimami
